### ISSUE TITLE
Oh, 您真能水，截图呢

### ISSUE THREAD

**Issue by yeshan333** [MrGo123/StudentCompanyManageSystem#1]

**Comment by MrGo123** [comment]
@yeshan333 Building。没玩过呀

**Comment by yeshan333** [comment]
？？？

**Comment by yeshan333** [comment]
> @yeshan333 Building。没玩过呀

Shit

**Comment by MrGo123** [comment]
应该OK了…………

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yeshan333"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 下午2:42
收件人:&nbsp;"MrGo123/StudentCompanyManageSystem"<StudentCompanyManageSystem@noreply.github.com&gt;;
抄送:&nbsp;"zymail68"<2573022290@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MrGo123/StudentCompanyManageSystem] Oh, 您真能水，截图呢 (#1)





  
@yeshan333 Building。没玩过呀
  
Shit

**Comment by MrGo123** [comment]
got that！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yeshan333"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 晚上6:50
收件人:&nbsp;"MrGo123/StudentCompanyManageSystem"<StudentCompanyManageSystem@noreply.github.com&gt;;
抄送:&nbsp;"zymail68"<2573022290@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MrGo123/StudentCompanyManageSystem] Oh, 您真能水，截图呢 (#1)





 
Closed #1.

**Comment by redhat123456** [comment]
👍
